# shellcheck shell=bash
# =============================================================================
# emit_conn_sampler.sh -- generate the per-run frontend sampler both arms run.
#
# SOURCE this file, do not execute it. It defines one function:
#
#     emit_conn_sampler <dest-path>
#
# and writes nothing until that function is called. The generated script is then
# started on EVERY serving node of the run, by both launchers.
#
# WHY THIS EXISTS AT ALL, and why it is not optional bookkeeping.
#
# On 2026-09-14 it was established that vLLM's --api-server-count does not do
# what it says: the sixteen API server processes share ONE listening socket
# (TECHNICAL_REPORT_1.tex Appendix A), so SO_REUSEPORT never balances anything
# and four of sixteen processes took every connection on every local-client run.
# Delivered throughput tracks the number of processes that actually received
# connections, not the flag -- three settings of A on the colocated arm gave
# 348.20, 462.82 and 342.89 tok/s, non-monotonic in A.
#
# THE DISTRIBUTION IS DECIDED IN THE FIRST SECONDS OF A BENCH AND CANNOT BE
# RECOVERED AFTERWARDS. `ss` reports live sockets; once the bench client
# disconnects there is nothing left to count, and no counter anywhere records
# what the split was. A run benched without this sampler running is a run whose
# throughput number has no denominator, and three such runs have already been
# spent finding that out. Start it before the bench, not after.
#
# WHY A SHARED EMITTER RATHER THAN A COPY IN EACH LAUNCHER. Same argument
# emit_common_env.sh makes about the environment and workload_profile.sh makes
# about the workload. The connection distribution is compared BETWEEN arms, so
# if colocated tallies by pid and disagg tallies by process name -- or one of
# them samples every 5 s and the other every 30 -- the two numbers are not the
# same measurement and the difference reads as a result. One copy.
#
# WHAT IS DELIBERATELY NOT SAMPLED: vllm:kv_cache_usage_perc.
#
# It is unusable at --api-server-count > 1 and sampling it produces a number
# that looks authoritative and is not. The gauges are multiprocess_mode
# "mostrecent" over per-frontend PARTIAL views, and vLLM disables its own
# periodic logger at client_count > 1 explicitly "to avoid incomplete stats"
# (loggers.py:1337-1341). Observed 2026-09-14: bit-identical values across 10 s
# while decode added thousands of tokens, and num_requests_running = 22 with
# only 18 connections open. CLOSED.md retired the standing requirement to sample
# it; zero preemptions plus the counter identity already answer what it was for.
# Do not add it back without an ASC=1 run to calibrate against.
#
# REQUIRED IN THE CALLER'S SCOPE: nothing. The generated script takes everything
# as arguments, because it runs on a node that has sourced no environment --
# started through `ssh -n <node> "setsid nohup bash ..."`, which carries neither
# the run's common_env.sh nor a login shell's PATH.
# =============================================================================

emit_conn_sampler() {
    local _dest=${1:?emit_conn_sampler: destination path required}

# QUOTED heredoc ('SAMPLEOF'). Everything in here resolves on the serving node
# at sampling time, not on the launcher's node now. There is nothing in this
# body that should be baked in, which is why -- unlike emit_common_env.sh --
# there is no unquoted half.
cat > "${_dest}" <<'SAMPLEOF'
#!/bin/bash
# Generated by emit_conn_sampler.sh. Runs ON a serving node, node-local.
#
#   sample_conns.sh <stop-marker> <out-file> <port|-> <interval-s> <label> [kind]
#
# `ss` and `pgrep` read the LOCAL process table and the LOCAL socket table, so
# this has to run on the node being measured -- running it from the launcher's
# node reports the launcher's node (MEMORY_2026-09-12h.md). /metrics likewise
# goes to 127.0.0.1 and not to the hsn0 address: the hsn0 route leaves the node
# and comes back, which works but means a sample can fail for a fabric reason
# that has nothing to do with the engine.
STOP_MARKER="$1"
OUT="$2"
PORT="$3"            # "-" on a headless node: no API server, no listening socket
INTERVAL="${4:-10}"
LABEL="${5:-$(hostname -s)}"
# serving | client. The client node is where the bench and the proxy are
# SUPPOSED to be, so finding them there is data; finding them on a serving node
# is a contaminated run. Same sampler either way -- one copy -- but the verdict
# differs, so it has to be told which kind of node it is on.
KIND="${6:-serving}"

# `-` is not "port unknown", it is "this node runs no frontend". A headless
# data-parallel node hosts an engine and TP workers and serves no HTTP at all,
# so there is no socket to distribute and no /metrics to scrape. It is still
# sampled, because the interesting question about a headless node is whether ITS
# workers are the slow ones -- an expert all-to-all completes at the speed of
# its slowest rank, exactly as a TP all-reduce does.
HEADLESS=0
[ "${PORT}" = "-" ] && HEADLESS=1

{
    echo "# node=$(hostname -s) label=${LABEL} kind=${KIND} port=${PORT} interval=${INTERVAL}s"
    echo "# start=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# kv_cache_usage_perc is NOT sampled: stale at ASC>1, see CLOSED.md 2026-09-14."
    if [ "${HEADLESS}" -eq 1 ]; then
        echo "# headless node -- no API servers, no listening socket, no /metrics."
    else
        # THE ONE-SECOND DIAGNOSTIC, captured once per run rather than typed by
        # hand when someone remembers. ONE LISTEN row means every API server
        # shares a single accept queue and --api-server-count buys nothing;
        # sixteen rows would mean a genuine SO_REUSEPORT group. This build
        # prints one row with N+1 processes attached -- the N children and the
        # parent that bound it -- every one of them at the same fd number, which
        # is the signature of one descriptor duplicated into identically spawned
        # children. TECHNICAL_REPORT_1.tex Appendix A.
        echo "# -- LISTEN rows on :${PORT} (1 row = one shared accept queue) --"
        ss -ltnp "( sport = :${PORT} )" 2>/dev/null | sed 's/^/# /'
        echo "# -- API server process count --"
        echo "# VLLM::APIServer procs: $(pgrep -fc 'VLLM::APIServer' 2>/dev/null || echo 0)"
    fi
    echo "# -- worker processes --"
    pgrep -a -f '[W]orker_TP' 2>/dev/null | sed 's/^/# /'
    echo "#"
    echo "# columns: ts | n_conn | n_srv | dist(desc) | running | waiting | psr"
} >> "${OUT}"

while [ ! -f "${STOP_MARKER}" ]; do
    TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

    if [ "${HEADLESS}" -eq 1 ]; then
        NCONN=0; NSRV=0; DIST="-"; RUN="-"; WAIT="-"
    else
        # Tally by pid, not by process name. Every API server has the same
        # name, and the whole finding is that they are not interchangeable.
        _pids=$(ss -tnp state established "( sport = :${PORT} )" 2>/dev/null \
                | grep -o 'pid=[0-9]*' | sort)
        # The FULL distribution, sorted descending -- not the count of nonempty
        # buckets. Two colocated runs at four effective servers, same pool, same
        # flag, same workload, delivered 342.89 and 391.81 tok/s, 14.3% apart,
        # and the shape accounts for about a quarter of that (CLOSED.md
        # 2026-09-14). The summary statistic drafted on 09-14 to replace the
        # shape -- inverse-Simpson over the connection counts -- predicted the
        # WRONG DIRECTION on the remote-client run and must not be used. Record
        # the shape; derive nothing from it here.
        DIST=$(printf '%s\n' "${_pids}" | uniq -c | sort -rn | awk '{printf "%s/", $1}')
        DIST="${DIST%/}"
        [ -z "${DIST}" ] && DIST="-"
        NCONN=$(printf '%s\n' "${_pids}" | grep -c 'pid=' )
        NSRV=$(printf '%s\n' "${_pids}" | sort -u | grep -c 'pid=' )

        M=$(curl -s -m 5 "http://127.0.0.1:${PORT}/metrics" 2>/dev/null)
        RUN=$(printf '%s' "${M}"  | grep '^vllm:num_requests_running' | awk '{print $2}' | paste -sd, -)
        WAIT=$(printf '%s' "${M}" | grep '^vllm:num_requests_waiting' | awk '{print $2}' | paste -sd, -)
        [ -z "${RUN}" ]  && RUN="-"
        [ -z "${WAIT}" ] && WAIT="-"
    fi

    # Which core each API server last ran on, and its state. On 2026-09-14 the
    # four servers holding connections were the only ones in state R and all
    # four sat on NUMA 3 alongside a local benchmark client, while all twelve
    # idle servers sat on NUMA 0 in do_epoll_wait -- no process pinned, every
    # affinity mask 0-287. That was observed by hand, once, and is the leading
    # unconfirmed explanation for the concentration. Recording it every sample
    # costs nothing and turns it into something that can be checked against a
    # run rather than remembered about one. `psr` is the last CPU the process
    # ran on; on this node cores 72i..72i+71 are NUMA i.
    if [ "${HEADLESS}" -eq 1 ]; then
        PSR="-"
    else
        PSR=$(ps -o pid=,psr=,stat= -C python3 2>/dev/null \
              | awk '{printf "%s:%s%s ", $1, $2, $3}')
        [ -z "${PSR}" ] && PSR="-"
    fi

    echo "${TS} n_conn=${NCONN} n_srv=${NSRV} dist=[${DIST}] running=${RUN} waiting=${WAIT} psr=[${PSR}]" >> "${OUT}"

    # The proxy, when it is on this node. `toy_proxy_server`, NOT `proxy`:
    # `pgrep -f proxy` matches the `ssh` wrapper that started it first and
    # returns the wrong pid, which is how the proxy's CPU was missed three
    # times running (MEMORY_2026-09-12h.md). Until it is measured, no TTFT
    # attribution on any disagg arm is quotable -- a single-process asyncio
    # proxy fronting the pair is the most likely thing to cap throughput, and a
    # cap there looks exactly like "disaggregation does not help".
    PP=$(pgrep -f toy_proxy_server 2>/dev/null | head -1)
    if [ -n "${PP}" ]; then
        PCPU=$(ps -o %cpu=,rss=,psr= -p "${PP}" 2>/dev/null | awk '{printf "cpu=%s rss=%sk psr=%s", $1, $2, $3}')
        echo "${TS} proxy pid=${PP} ${PCPU}" >> "${OUT}"
    fi

    # The benchmark client. On a CLIENT node that is where it belongs and its
    # CPU is data -- the client node also hosts the proxy, and two frontend-side
    # processes on one node can contend with each other even though neither is
    # on a serving node. On a SERVING node it is a rule violation: moving the
    # client off the serving node was worth +37.7% throughput and -14.4% engine
    # work per token on an otherwise identical run (report S7). Same probe, two
    # verdicts.
    BP=$(pgrep -f 'vllm bench|benchmark_serving' 2>/dev/null | head -1)
    if [ -n "${BP}" ]; then
        if [ "${KIND}" = "client" ]; then
            BCPU=$(ps -o %cpu=,rss=,psr= -p "${BP}" 2>/dev/null | awk '{printf "cpu=%s rss=%sk psr=%s", $1, $2, $3}')
            echo "${TS} bench pid=${BP} ${BCPU}" >> "${OUT}"
        else
            echo "${TS} *** BENCH CLIENT IS ON THIS SERVING NODE (pid=${BP}) -- engine numbers contaminated ***" >> "${OUT}"
        fi
    fi

    sleep "${INTERVAL}"
done
SAMPLEOF
chmod +x "${_dest}"
}

# -----------------------------------------------------------------------------
# summarize_conn_sampler <sampler-log> <label>
#
# Read back what the sampler recorded, for the launcher's teardown banner. Kept
# beside the emitter so the reading and the writing cannot drift.
#
# Reports the PEAK, not the last sample or the mean. The distribution is set
# when the bench opens its connections and is stable for the life of the launch
# -- the same three processes led all three colocated benches against one launch
# on 2026-09-14, forty minutes and two arrival patterns apart -- so the sample
# taken at full load is the one that describes the run. Samples taken between
# benches describe an idle server and would drag a mean toward zero.
# -----------------------------------------------------------------------------
summarize_conn_sampler() {
    local _log=$1 _label=$2
    if [ ! -s "${_log}" ]; then
        echo "  ${_label}: no samples -- the sampler never started. Any throughput"
        echo "    number from this run has no measured effective-server count."
        return
    fi
    # The client node's line is about the proxy, not about connections: it has
    # no listening socket, and the proxy's CPU is the number four disagg runs
    # have owed since 2026-09-12. Until it is measured, no TTFT attribution on
    # any disagg arm is quotable -- a single-process asyncio proxy fronting the
    # pair is the most likely thing to cap throughput, and a cap there looks
    # exactly like "disaggregation does not help".
    if grep -q 'kind=client' "${_log}" 2>/dev/null; then
        awk -v lbl="${_label}" '
            /proxy pid=/  { c=$4; sub("cpu=","",c); if (c+0 > pmax) pmax=c+0; pn++ }
            /bench pid=/  { c=$4; sub("cpu=","",c); if (c+0 > bmax) bmax=c+0; bn++ }
            END {
                if (pn) printf "  %s: proxy peak %.1f%% CPU over %d samples\n", lbl, pmax, pn
                else    printf "  %s: proxy never seen -- pgrep -f toy_proxy_server found nothing\n", lbl
                if (bn) printf "    bench client peak %.1f%% CPU over %d samples (expected here)\n", bmax, bn
                if (pn && pmax > 90)
                    print  "    *** proxy above 90% of one core: it is a candidate ceiling. ***"
            }' "${_log}"
        return
    fi
    grep -q 'headless node' "${_log}" 2>/dev/null && {
        echo "  ${_label}: headless, no frontend (by design)"
        return
    }
    awk -v lbl="${_label}" '
        /n_conn=/ {
            nc = $2; sub("n_conn=", "", nc)
            if (nc + 0 > peak_nc) {
                peak_nc = nc + 0
                ns = $3; sub("n_srv=", "", ns); peak_ns = ns
                d  = $4; sub("dist=", "", d);    peak_d  = d
            }
            n++
        }
        /BENCH CLIENT IS ON THIS SERVING NODE/ { contaminated++ }
        END {
            if (peak_nc + 0 == 0) {
                printf "  %s: %d samples, never saw a connection\n", lbl, n
            } else {
                printf "  %s: peak %d connections over %s servers, dist %s  (%d samples)\n",
                       lbl, peak_nc, peak_ns, peak_d, n
            }
            if (contaminated > 0)
                printf "    *** %d samples saw a bench client on this serving node ***\n", contaminated
        }' "${_log}"
}
